# Generated by Django 4.2.4 on 2023-09-19 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Senai_Equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 19, 20, 30, 1, 415078)),
        ),
        migrations.AlterField(
            model_name='equipamentos',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 19, 20, 30, 1, 415078)),
        ),
        migrations.AlterField(
            model_name='users',
            name='senha',
            field=models.CharField(max_length=30),
        ),
    ]
